### ISSUE TITLE
Request to submit 'v1.0.1' release

### ISSUE THREAD

**Issue by jeff1evesque** [claranet/puppet-timezone#21]
Issue #20 is fixed if I change my `Puppetfile`:

``` ruby
## Install Module: timezone
mod 'timezone',
  :git => 'git@github.com:BashtonLtd/puppet-timezone.git',
  :ref => 'v1.0.0'
```

to the following current status of the `master` branch:

``` ruby
...
## Install Module: timezone (from master)
mod 'timezone',
  :git => 'git@github.com:BashtonLtd/puppet-timezone.git',
  :commit => '1672983'
```

**Note:** the commit hash 1672983, corresponds to the current status of the `master` branch.

**Comment by cdenneen** [comment]
👍

**Comment by craigwatson** [comment]
Hi all,

Apologies for the delay here, following the move of GitHub org, we will be releasing version 2.0.0 to the Forge shortly, rather than 1.0.1.

Thanks,
Craig
